spring:
  datasource:
    username: admin
    password: pwd
    url: jdbc:h2:mem:./db/testdb;
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/changelog-master.yml

job-vacancy-url: ${VACANCIES_URL:https://www.arbeitnow.com/api/job-board-api}